### ISSUE TITLE
10 - Intro to Docker and Docker Compose

### ISSUE THREAD

**Issue by TheBeege** [YUHEE1984/CatsOneday#11]
# Goal

Learn about Docker to make local development easier.

# Context

## What's Docker?

Docker is a way to easily run software in a portable, standalone manner. Today, you'll learn about what Docker is and how you can use it to run supporting services like databases during your development.

First, you need to understand the structure of Docker:

![Docker structure](https://docs.docker.com/get-started/images/docker-architecture.webp)

When you install Docker, you install both a server and a client on your computer. The server is responsible for doing most of the work. The client is a command-line tool that you use to interact with the Docker server.

The Docker server manage two things: images and containers. These names can be confusing. 

Let's address some terminology. This is less important, but I'm sure you'll ask about it. The name "image" in this context is a reference to old technology. Back in the days of compact disks (CDs), computers would shine a laser at the disk and read the reflected light as data. Observing how light reflects off a surface is how we see things in real life. The way the CD was made reflects light in a specific way, much like paint on a canvas is arranged to reflect light in a specific way. Hence, the data on a CD is called an "image." CDs were used for many different purposes, including installing operating systems and application software. We called the data put on the CD to install the OS or software an image. Later, we came up with the idea of a "virtual machine," which is basically a computer inside a computer. The virtual machine includes an operating system and installed software. Often, we would create a CD image and use that to install the virtual machine. Over time, as the internet became faster and USB drives became common, rather than use CDs, we stored the image as a normal file. If you've ever seen an ISO file, you've seen one of these image files. In the end, image files, or ISO files, are basically installable operating systems or software, and they were widely used to create and distribute virtual machines. In more recent times, Docker has come to replace virtual machines for specific uses, but the terminology remains the same.

A Docker "image" is packaged software to be run using Docker. There are Docker images for many different software - databases, message queues, web servers, and much more. A Docker image is what is usually downloaded from the internet and used on your computer.

A Docker "container" is an instance of that sofware actually running. You can almost think of a Docker image like a Java class and a Docker container like a Java object. You could download a web server Docker image and run 100 Docker containers from that image, meaning you would be running 100 web servers. 

Lastly, a registry is just a place where images are stored and made available for download. Docker Hub is the most popular registry, but anyone can run their own Docker registry. 

We're not going to cover extensions and plugins for now, as you're unlikely to need them.

So why use Docker? Why not just download the web server itself and run it 100 times? One key things is consistency. Docker includes an operating system environment. It includes configuration files and library files and various other dependencies already written and stored in the proper places. By ensuring that the environment where the software is running is uniform, it's easier to distribute the software in a reliable way. Additionally, Docker containers are isolated. When a container is deleted, all of its data is completely gone (unless you're using volumes, but more on that later). Installing and uninstalling software usually leaves some kind of extra files or configurations that can be difficult to find and cleanup. Lastly, is ease of use. Docker containers are usually designed such that they'll run the software when the container starts. You don't need to actually understand how to run the software: the container does it for you. This means that if you know how to run Docker, you now know how to run thousands of different kinds of software.

## Docker Compose

There is a specific component of Docker called Docker Compose that you'll use very often. Docker Compose allows you to define and configure Docker containers in advance and run them all with a single command. This is very useful when you're developing software that communicates with many other running software. A common use case for backend engineers is running a database using Docker in order to test your application's communication with a database. This is actually what we'll be doing today.

## YAML
YAML is "Yet Another Markup Language" or "YAML Ain't Markup Language," depending on whom you ask. YAML is similar to JSON in that you can define data in a way that's easy for humans to read. Here's an example:

```yaml
root:
    child:
        some_list:
        - list item
        - list_item_object_key: value
          another_object_key: in that list item
        - another list item
```

Here's the same data in JSON:

```json
{
    "root": {
        "child": {
            "some_list": [
                "list_item",
                {
                    "item_item_object_key": "value",
                    "another_object_key": "in that list item"
                },
                "another list item"
            ]
        }
    }
}
```

You can see that YAML is more compact, though some think it's more difficult to read than JSON. YAML is a "superset" of JSON, meaning that YAML includes JSON and more. Technically, that JSON data is also YAML data. So if you're working alone and prefer JSON, you could write "YAML" files in JSON format. In teams, this is less common.

So why are we talking about YAML? YAML is the format used in Docker Compose files. Today, you'll use YAML to set up your development environment.

# Steps

## Installing Docker

1. Install Rosetta 2 to install required MacOS components: `softwareupdate --install-rosetta`. Just run this in a terminal. The location doesn't matter.
2. Go to [the Docker installation page for MacOS](https://docs.docker.com/desktop/install/mac-install/).
3. Click the "Docker Desktop for Mac with Apple silicon" button to start downloading the installer.
4. Open the `.dmg` and install as normal. When finished, run Docker Desktop if it doesn't start automatically.
5. Open a terminal and run `docker run --rm hello-world`. You should see a message printed out explaining that Docker is running properly.

Done! They try to make it easy for you. That last command told Docker to run an image named `hello-world` as a container. You can see that [image on the Docker Hub registry](https://hub.docker.com/_/hello-world/). When the container ran, the program inside it printed to the terminal and then exited. The `--rm` flag just tells Docker to remove the container once it finishes running, since containers are preserved by default. Congratulations on running your first Docker container!

## Now With Docker Compose

[Docker Compose reference](https://docs.docker.com/compose/compose-file/)

1. Create a file in your project folder: `compose.yml`.
2. Write `services:` in the file as the first line. This section will define what containers we'll run.
3. Create a sub-object called `hello:`. We're going to define a new service that we're calling `hello`. Your YAML should look like this:
    ```yaml
    services:
        hello:
    ```
4. Under `hello:`, define a new object property `image` with a value of `hello-world`. 
    * It should look like this:
        ```yaml
        services:
            hello:
                image: hello-world:latest
        ```
    * The image specifies the Docker image to use for the container. In this case, we're using the [hello-world](https://hub.docker.com/_/hello-world/).
    * The `:latest` part is a `tag` for the Docker image. Software often has many differnet versions, so Docker images are the same. The `:latest` tag just specifies the latest, stable version of the image. Each image will have its own set of versions, but `latest` is quite common. Just be aware that the version specified by `latest` will change quite often.
5. In a terminal at your project folder, run `docker compose up`. You'll see that the `hello-world` image's program runs again. You'll also noticed that each line is prefixed with `hello-1`. Why? This is how Docker Compose informs you that the text output is from the `hello` service and is the first (`1`) container in that service. (You can run multiple containers in a single service, but we're not covering that.)
6. Run `docker compose down` to clean up the container.

Well done! You've run your first container with Docker Compose! Now, let's make it more useful...

## Running a Database With Docker Compose

Note that there is a cheatsheet at the bottom if you run into problems. Remember, the exact syntax is something you can lookup. Understanding how things work is the important part.

1. Remove the `hello` service and all of its sub-objects from your `compose.yml`.
2. Define a new service: `database`.
3. Set the image for that service to `postgres:latest`.
    * [PostgreSQL](https://www.postgresql.org/) is a very popular, free, open source database.
4. Define a new service: `ui`.
5. Set the image for the `ui` service to `adminer:latest`.
    * [Adminer](https://www.adminer.org/) is a lightweight utility for interacting with a database using a web interface.
    * Without Adminer, you would need to install the PostgreSQL client utilities on your computer in order to check the database. (Though technically, we could do that with Docker, too.) While you may want to do that at some point in the future, it's not necessary now.
6. We need to set a password to login to the database. The [PostgreSQL image](https://hub.docker.com/_/postgres/) allows us to do this with environment variables. In the `database` service, add a new object: `environment:`.
    * What's an environment variable? It's a variable just like in Java with some key differences. It's set **outside** of your program. It's set in the "environment" that your program runs in. Why? This allows whoever is running your program to set configurations using these variables without needing to actually change your program.
7. Under `environment:`, add a new property: `POSTGRES_PASSWORD: postgres`. This will set the PostgreSQL superuser password to the text `postgres`.
    * How did I know all of this? I didn't. It's in the [PostgreSQL image documentation](https://hub.docker.com/_/postgres/). Most images will have instructions on how to configure and use them.
8. We need to expose the Adminer port to allow you to view Adminer in your web browser. Under the `ui` service, add a new object: `ports:`.
9. Under `ports:`, create a new list item with the following object that looks like this (including `ports`):
    ```yaml
    ports:
    - target: 8080
      published: 8080
    ```
    * What is a port? If you think of a computer like a house, a port is like a door. It allows others to communicate or even transfer into and out of a computer, like a person may talk with someone at their door or go into or out of their door. Each port is defined by a number, up to 65535.
    * Why port 8080? Ports below 1000 are reserved by the operating system and require specific permissions to use. Port 80 is the default HTTP port. People often use 8000 or 8080 to get a number similar to 80 but above 1000.
    * There is a shorter version to write this port configuration: `- "8080:8080"`. I don't like this because I can't remember which port goes on which side of the colon (`:`). I'd prefer to type more now and make it easier to read later.
    * Why do we need to set the ports like this? The Adminer application runs on port 8080 by default. Docker Compose allows containers to talk to each other, but it isolates the containers' network from your computer's network. This means your computer can't freely talk to the containers. By specifying these ports, we're telling Docker Compose to expose port 8080 in the container as port 8080 on your computer.
10. Let's run it! Run `docker compose up` in your terminal in your project directory.
11. Once Docker Compose is finished printing things, visit [http://localhost:8080/](http://localhost:8080/) in your browser. You'll see the Adminer interface!
12. Enter `PostgreSQL` as the system, `database` as the server, `postgres` as the user, and `postgres` as the password. Then click Login.
    * Why is the server `database`? Docker Compose sets up a local [name server](https://en.wikipedia.org/wiki/Name_server) ([Korean](https://ko.wikipedia.org/wiki/%EB%84%A4%EC%9E%84_%EC%84%9C%EB%B2%84)) that runs in your containers' network. This name server creates names that match the names of your Docker Compose services. Within your Docker Compose containers, you can just specify the name of the service you want to connect to, and Docker Compose will handle name resolution and routing for you. In our case, Docker Compose will route Adminer to our PostgreSQL container when Adminer tries to connect to `database`.
13. Observe the default PostgreSQL objects. You don't need to understand them, yet, but we want to make sure you can see them.
14. Hit `ctrl + c` in your terminal to stop the Docker containers.
15. Run `docker compose down` to clean everything up, deleting the containers.

Great job! You've run your first database server! Using Docker Compose, you can set up and run your database with a single command. It even includes a web interface for you to check your data while your developing. This will be very useful later on.

## Persisting Our Data

There's one problem: when we take down our database, all of the data is gone. You probably don't want your data to disappear between development sessions, so let's fix that.

1. At the bottom of your `compose.yml` file, add some new lines at the root level. (The root level means no indentation.)
2. Define a new section: `volumes:`.
    * What's a volume? A volume is durable storage that could be moved between computers. In this case, a volume is a way to store data from Docker containers that will persist even if the Docker container is deleted. The volume can be attached to a future Docker container to re-use the data.
3. Create a new sub-object under `volumes` called `db-data:`. This one is unusual in that we don't actually need any contents in this object. Its existence alone is enough to create the volume.
4. Under your `database` service, add a new `volumes:` sub-object.
5. We're going to create a list with an object like below (including `volumes:`):
    ```yaml
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/postgresql/data
    ```
    * What does this do? This tells Docker that we're going to use a volume. The volume we're going to use (`source`) is the `db-data` volume we defined in step 3. The `target` is what folder inside the container should use the volume. So any data in the container written to that folder is saved in the volume, meaning it will persist even if the container is deleted.
    * Why `/var/lib/postgresql/data`? That's the default location that PostgreSQL stores all of its data.
6. Run `docker compose up` to run your containers again.
7. Visit adminer at [http://localhost:8080/](http://localhost:8080/) in your browser.
8. Again, login with `PostgreSQL` as the system, `database` as the server, `postgres` as the user, and `postgres` as the password.
9. Click the `Create database` link.
10. Enter `test` and click save. You'll see that `DB` on the left is set to `test`.
11. Click `database` at the top. You'll see `test` in the table of databases.
12. Hit `ctrl + c` in your terminal.
13. Run `docker compose down`. This deletes the containers and all their data.
14. Run `docker compose up` to bring them up again. Login to Adminer, and you'll see that the `test` database is still there.
    * If you were to run it again without the `volumes` section in your `database` service, that `test` database would not appear. It would be deleted with the Docker container.

Nicely done! Today was a hard one, but you did it! You now have a PostgreSQL database running that you can use with your CatsOnday program. You can also view and work with the data using the Adminer interface. This is absolutely critical if you want to save your cute cats to see later.

# Final Compose File (Cheatsheet)
```yaml
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
        - type: volume
          source: db-data
          target: /var/lib/postgresql/data
    
    ui:
        image: adminer:latest
        ports:
        - target: 8080
          published: 8080

volumes:
    db-data:
```

# Other Notes

Docker made a change to their licensing in recent years:

> Docker Desktop is free to use as part of the Docker Personal subscription for individuals, non-commercial open source developers, students and educators, and small businesses of fewer than than 250 employees AND less than $10 million in revenue. Commercial use of Docker Desktop at a company of more than 250 employees OR more than $10 million in annual revenue requires a paid subscription (Pro, Team, or Business).

Be wary of this, as Korean companies tend to be bad at checking software licenses. As an alternative, companies can look into [Rancher Desktop ](https://rancherdesktop.io/) or [podman](https://podman.io/). Rancher is probably better if the company isn't using Kubernetes.

**Comment by YUHEE1984** [comment]
I don't fully understand it yet, but I think I can agree and like the convenience of this whale.

**Comment by YUHEE1984** [comment]
Review completed
