### ISSUE TITLE
04 - Dependencies and Laziness

### ISSUE THREAD

**Issue by TheBeege** [YUHEE1984/CatsOneday#4]
# Goal
It's time to setup your first dependency and save yourself some typing effort.

In this task, you'll add the Lombok library as a plugin dependency. The Lombok library is commonly used to reduce the amount of boring code you need to write. At compile-time, it automatically generates code for you based on "annotations." An annotation is a small bit of code you add that starts with the `@` symbol. You'll see how this works, shortly.

# Steps
## Add Lombok as a Plugin Dependency
1. Open `build.gradle` in our root project directory.
2. Locate the `plugins` section.
3. Add `id "io.freefair.lombok" version "8.6"` somewhere inside the `plugins` section.

That's it! The `id` specifies which library you want to include in your project. Where did this project come from? There's a central repository where library developers publish their libraries for others to download. You generally don't need to worry about this. The `version` part specifies the version of the plugin. 

## Cleaning Up Code
1. Open your `Cat.java` file.
2. Towards the top of the file, after the `package` line, let's import our first annotation: `import lombok.AllArgsConstructor`.
    * The `AllArgsConstructor` annotation will automatically generate a constructor method that has every attribute of the class as a parameter and assigns the parameter values to those class attributes. Basically, it generates the same code as the constructor you wrote in #2.
3. Immediately above your class declaration (`public class Cat`), add the `@AllArgsConstructor` annotation.
5. Remove the constructor method you wrote last time.
6. Try a `./gradlew run`. It still works! Lombok generated the constructor for you.

## More Lombok Things
1. Change all of the attributes in your `Cat` class to `private`.
2. Add another import: `import lombok.Getter`.
3. Above the `Cat` class, add the `@Getter` annotation.
4. Import `lombok.Setter`.
5. Above your `weightInKg` attribute, add the `@Setter` annotation.
7. In `App.java` in the `main`, print out the the cat's name and weight using `getName()` and `getWeight()`.
8. After that, use `setWeight(...)` on the cat to set its weight.
9. Finally, print out the cat's name and weight again. Well done!

Note that you didn't have to write getter or setter functions directly. The Lombok annotations provide these functions for us automatically. Many Java engineers use Lombok to reduce the amount of code they need to write.

So we covered how to add a dependency, in this case, a plugin. We went over using class-level Lombok annotations and attribute-level Lombok annotations, and we demonstrated them working. In the future, especially with Spring, you'll set up lots of dependencies, and Lombok will save you a lot of time.

**Comment by YUHEE1984** [comment]
I think I love Lombok >-<

**Comment by YUHEE1984** [comment]
Reviewed it.
