### ISSUE TITLE
07 - Your First Server

### ISSUE THREAD

**Issue by TheBeege** [YUHEE1984/CatsOneday#7]
# Goal
Build a server!

# Background
We're not going to write any Java today. We're doing something new!

We'll create a a tiny, tiny web server. It will serve one web page. It will be stupid and boring, but it will teach you how a server works without anything too complicated. Let's do it.

## What is a Server?
A server serves. Lesson over! Really, a server is part of the "[client-server model](https://en.wikipedia.org/wiki/Client%E2%80%93server_model)" ([Korean](https://ko.wikipedia.org/wiki/%ED%81%B4%EB%9D%BC%EC%9D%B4%EC%96%B8%ED%8A%B8_%EC%84%9C%EB%B2%84_%EB%AA%A8%EB%8D%B8)). In the client-server model, some process is able to provide data to other processes that ask for it. This is called the server. Another process requests data from the server. This is called the client. These two processes can be two processes on the same machine or computers on opposite sides of the planet through the internet. When we say "server," we really mean some kind of program that responds to requests or "serves" some data.

## What is a Web Server?
First, you need to understand what the web is. The web is meant to be a metaphor for a spiderweb. A spiderweb is composed of many, many connections in many different directions where there isn't any kind of hierarchy. The [web](https://en.wikipedia.org/wiki/World_Wide_Web) ([Korean](https://ko.wikipedia.org/wiki/%EC%9B%94%EB%93%9C_%EC%99%80%EC%9D%B4%EB%93%9C_%EC%9B%B9)) refers to computers connected through the internet that can talk to each other. Specifically, these computers share content in the form of "web pages." To ensure that all of these computers can understand these web pages, "hypertext" was invented. "Hyper" means "super." So it's... super... text... Listen, computer scientists aren't hyper creative 😅 But while not very creative, it is descriptive. 

## What is Hypertext?
[Hypertext](https://en.wikipedia.org/wiki/Hypertext) ([Korean](https://ko.wikipedia.org/wiki/%ED%95%98%EC%9D%B4%ED%8D%BC%ED%85%8D%EC%8A%A4%ED%8A%B8)) is what makes web pages. The page you're looking at now is just text. This text includes the text on the page that you're reading, but it also includes text that tells your web browser where to find images or where a text input form is or where a link should lead to. Hypertext is what makes the web work.

## How Does the Web Share Data?
A web server serves hypertext. It allows another process, like the web browser on your computer, to request hypertext, and it sends that hypertext to your web browser as a response to the request. This transactional nature - request and response - is a key part of how hypertext is exchanged across the web. In fact, there's a specific way (protocol) that describes how computers across the internet can exchange (transfer) hypertext. Believe it or not, it's called hypertext transfer protocol, or [HTTP](https://en.wikipedia.org/wiki/HTTP) ([Korean](https://ko.wikipedia.org/wiki/HTTP)). You've seen web addresses like http://zombo.com/, right? That `http` part tells your browser that it can use hypertext transfer protocol to retrieve hypertext from the server.

## What is HTTP?
So now you know what purpose HTTP serves, but what **is** HTTP?

It's a set of rules that defines how two computers, a client and server, can exchange hypertext. Yes, yes, I told you that already, but the rules part is important. So here are some of the rules:

1. A client must connect to a server and make a request, and the server must send a response. This is a transaction. The connection must be closed when the transaction is completed.
2. The structure of requests and responses in an HTTP transaction is defined by human-readable text.
3. Requests and responses are both composed of a head and body. A head includes metadata about the request. The body contains the content of the request.
4. The first line of a request or response indicates whether the message is a request or response. Requests and responses use a different format for this first line.
    * Request format: `HTTP_METHOD path http_version`
        * Example: `GET /news HTTP/1.1`
    * Response format: `http_version status_code status_name`
        * Example: `HTTP/1.1 200 OK`
5. There are "verbs" that define different types of operations a client requests a server to do. These are called [HTTP methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) ([Korean](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods)). The most popular ones are below:
    * GET
    * POST
    * PUT
    * PATCH
    * DELETE
    * OPTIONS
6. The "path" describes a resource on the web server that the client wants to interact with. They start with the "root" `/`. Resources are below the root, similar to Unix filesystem structures, e.g. `/library/books/10/chapters/3.html`.
7. Web servers respond with a [status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) ([Korean](https://ko.wikipedia.org/wiki/HTTP_%EC%83%81%ED%83%9C_%EC%BD%94%EB%93%9C)) indicating the results of the client's request. They're 3-digit codes where the first digit is the category of status. The categories are listed below:
    * 1xx - Continue
    * 2xx - Success
    * 3xx - Redirect
    * 4xx - Client error
    * 5xx - Server error
8. After the first line, head metadata is arranged in key-value pairs. The format is `Key: Value\n`. The key must be followed by a colon. The value must follow the colon. A newline indicates the header key-value is finished. A single key-value pair is called a "header."
9. Two newlines separate the request head and the body.
10. The body can contain any data, including binary data like images.

There are more rules, but these are the main ones you need to understand. There are also some very common headers that you'll learn over time. So here's an example HTTP request:
```http
GET / HTTP/1.1
Host: localhost
Accept: text/html
Connection: keep-alive
```

Note that the request has no body. There's no data it needs to send to the server, since it's just requesting data. Some requests do need to send data, but not this example.

Here's an example response:
```http
HTTP/1.1 200 OK
Content-Type: text/html
Connection: keep-alive

<!DOCTYPE html>
<html>
  <body>
    <h1>Hello, world!</h1>
  </body>
</html>
```

While very minimal compared to the real world, this could theoretically be a valid HTTP request/response exchange.

As a web backend engineer, you need to build your server to understand HTTP requests and server HTTP responses. Fortunately, most web server frameworks do this formatting and header construction for you. However, it's useful for you to understand when testing and troubleshooting.

# Steps
## The Server Response
1. Create a new folder somewhere on your computer, not in your CatsOneday project folder.
2. In that folder, create a new file: `hello.http`.
3. Put the following content into that file:
```http
HTTP/1.1 200 OK
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html>
  <body>
    <h1>Hello, world!</h1>
  </body>
</html>
```
This is the web page your web server will serve to clients.

## The Server
1. Create a new file in the same folder: `server.sh`.
2. Paste this into the file:
```shell
#!/bin/sh

trap exit EXIT INT TERM HUP

while true
do
  netcat -l -p 8000 -w 1 < hello.http &
  wait
done
```
* This is a `shell` script. Your terminal can understand this scripting language and run basic programs.
* `trap` is a way to catch signals, like how to exit the program.
 * `netcat` is a utility for doing basic network operations. We're using this to create our tiniest server.
3. Install netcat with `brew install netcat`.
4. Set execute permissions on the server script so you can actually run it: `chmod u+x server.sh`.
    * The `chmod` command is used to change permissions on files. In this case, we're adding (`+`) the e`x`ecute permission for the owning `u`ser: `u+x`. Your user is the owning user because your user created the file.
5. Run the server: `./server.sh`

## The client
Surprise! It's your browser.
1. Open your browser.
2. Go to [http://localhost:8000/](http://localhost:8000/)
    * In case it doesn't work, try `curl http://0.0.0.0:8000/ -v`
3. In your browser, hit `Command`+`Option`+`i` to bring up developer tools.
4. Click the network tab.
5. Refresh the page.
6. In the developers tools, click the line on the left side where the `File` is `/`.
7. Look at the Request Headers and Response Headers

## Cleanup
1. In the terminal where you ran the server, hit `Control`+`c` to kill the server.
2. You can delete the folder containing these files if you like.

Congratulations! You ran your first web server! It was very simple, but you did it. In this case, our web server only served a specific HTTP response that was missing a lot of normal headers, but it was still good enough for our browser to understand and display. From now on, the servers you write will be much more complicated but much more complete.

# Supporting Resources
* [Mozilla Developer Network (MDN) on the Basics of HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP) ([Korean](https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP))

**Comment by YUHEE1984** [comment]
Review completed
