### ISSUE TITLE
08 - Your First Spring Boot Project

### ISSUE THREAD

**Issue by TheBeege** [YUHEE1984/CatsOneday#8]
# Goal
Convert our project to a Spring Boot project

# Background
[Spring Boot](https://spring.io/projects/spring-boot) is the most popular way to create web services in Java. The Spring Framework has been around for a long time - since 2002. One key idea behind Spring is [inversion of control](https://en.wikipedia.org/wiki/Inversion_of_control) ([Korean](https://ko.wikipedia.org/wiki/%EC%A0%9C%EC%96%B4_%EB%B0%98%EC%A0%84)) (Note that the Korean example is absolutely terrible. Maybe you could fix it, someday). The basic concept is that you don't set up the server yourself. You just define the "business logic," and the application framework (Spring) handles all the work of setting up the server, binding to the port, setting up a listener, encoding things to/from HTTP, etc. Basically, you can focus on your program's interesting logic, and the framework can handle all of the boring stuff.

The Spring Framework previously used a bunch of XML and a lot of complex, strange features of Java, but the modern version is much, much simpler. This modern version, Spring Boot, instead uses "annotations." Remember how we used Lombok to write `@Getter` or `@AllArgsConstructor` to have it generate code for us? Those `@Something` bits are called annotations. Spring Boot allows you to create classes and annotate them to fulfill specific roles in the application. We won't focus on the annotations too much in this session, but it's important to understand their purpose.

To set up a Spring Boot project, the easiest way is to use Spring Initalizr. Yes, Inititializr is an incorrect spelling of "initializer." It's marketing nonsense. Anyway, Spring Inititializr is a website to help you generate all the files needed for a Spring Boot project. We'll use this to set up your first Spring Boot project.

Note that we'll add a lot of configurations that you won't use in this assignment. We're just adding in the configuration now to save time later.

# Steps

## Generating the Spring Boot Project

First, let's use Spring Initializr to set up our project files.

1. Go to the [Spring initializr](https://start.spring.io/).
2. Select "Gradle - Groovy" as the Project, "Java" as the Language, and "3.3.2" for Spring Boot. 
    * What are all these versions? When you see SNAPSHOT, it means that it's a version in development. Generally, you want to choose the latest version that's not a SNAPSHOT version. Spring also uses the `-M#` convention to mark a development version that has hit a numeric milestone. You can ignore these, too.
3. For Group, enter `org.yuhee`.
4. For Artifact, enter `catsoneday`.
5. For Name, also enter `catsoneday`.
6. For Description, write a short description of your application.
7. Package name should be automatically generated. You can skip it.
8. For Packaging, leave "Jar" selected.
9. For Java, choose your current Java version. Use `java -version` to see what version you're using.
10. Next, we need to choose our dependencies with the "Add dependencies..." button on the right. Don't worry about understanding each one for now. We'll get to that later. For now, just add the items from the below list. Note that you can hold the `ctrl` key (or maybe `cmd` on Mac?) to select multiple at once.:
    * Developer Tools
        * Spring Boot DevTools
        * Lombok
        * Spring Configuration Processor
    * Web
        * Spring Web
        * Jersey
12. Click the Generate button at the bottom. This will download a zip file.

## Merging Our Project

Now that we've generated the project, let's use it for the Catsoneday project.

1. Open the zip file, open the `catsoneday` folder inside the zip file, and copy the contents into your project folder. You'll be asked to replace files with the same name. Say yes to replacing/overwriting those files.
2. Run the below commands to clean things up. Don't worry about understanding them. You wouldn't normally need to do this.
    ```shell
    cp -r app/src/* src/
    rm src/test/java/org/yuhee/catsoneday/AppTest.java
    rm -rf app
    ```
3. Fix the permissions on `gradlew` by running `chmod u+x gradlew`.
4. Note that Spring Boot has changed Gradle configurations such that `./gradlew run` won't work anymore. They removed the `run` task. Instead, use `./gradlew bootRun` to try running the application.
    * "But Beege! Where are my cats?!" Yes, we haven't brought your cats into the Spring Boot application, yet. Let's fix that next.
5. You'll see that it prints a lot of text and then blocks. You can use `ctrl + c` to stop the application.
6. In your `src/main/java/org/yuhee/catsoneday/CatsonedayApplication.java` file, add the below method into the `CatsonedayApplication` class:
    ```java
    @Bean
    public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
        return args -> {

            // Paste your code here!
        };
    }
    ```
7. Add the below imports, as well:
    ```java
    import org.springframework.boot.CommandLineRunner;
    import org.springframework.context.ApplicationContext;
    import org.springframework.context.annotation.Bean;
    ```
8. Copy the code from your `App.java` into `CatsonedayApplication.java` in place of the comment `// Paste your code here!`
9. Remove the line `System.out.println(new App().getGreeting());`.
10. Run `./gradlew bootRun` again to run your application. You should see your print messages again.
11. Hit `ctrl + c` to stop the application.

Well done! You've run your first Spring Boot application! We generated a Spring Boot project using Spring Initializr and set up the Catsoneday project to be part of the Spring Boot project. Next, we'll turn your cats into Spring Boot models and show them via the API.

**Comment by YUHEE1984** [comment]
!!!!!

**Comment by YUHEE1984** [comment]
Review Completed.
